### ISSUE TITLE
Zettel bearbeiten

### ISSUE THREAD

**Issue by NJona** [NJona/Kanban-Board#10]
Soll es möglich sein die Zettel zu bearbeiten und wenn ja überall, oder nur in bestimmten Spalten?

**Comment by highperformancedevelopments** [comment]
In Mail vom 13.10.2017 Antwort beim Kunden angefordert.

**Comment by highperformancedevelopments** [comment]
AW Kunde 13.10.2017:

Anforderung:
Jede Aufgabe soll auf einem Zettel festgehalten werden.
Frage:
Soll es eine Bearbeitungsmöglichkeit für bereits erstellte Zettel geben? Wenn ja soll die Bearbeitung in allen Spalten möglich sein oder nur in bestimmten. Wenn die Bearbeitung beschränkt werden soll, bitte die Spalten angeben, in welchen die Bearbeitung möglich sein soll.

> Ahmen Sie am besten das Verhalten von echten Zetteln nach. Dort kann man Text durchstreichen, ergänzen und Post-its hinhängen

**Comment by highperformancedevelopments** [comment]
Intern:
Eindeutig geklärt evtl. bei Implementierung nochmal genaue RÜ bzgl. machbarkeit und Details - closed.
