### ISSUE TITLE
Kategorien

### ISSUE THREAD

**Issue by NJona** [NJona/Kanban-Board#11]
Kann ein Zettel mehreren Kategorien zugeordnet werden, oder nur einer?

**Comment by highperformancedevelopments** [comment]
In Mail vom 13.10.2017 Antwort beim Kunden angefordert.

**Comment by highperformancedevelopments** [comment]
AW Kunde 13.10.2017:

Jede Aufgabe soll einer Kategorie zugewiesen werden können.
Frage:
Soll es möglich sein, Zettel zu mehreren Kategorien zuweisen zu können?

> Nein, vorerst nicht

**Comment by highperformancedevelopments** [comment]
Intern:
Somit Vorerst eindeutig geklärt - reopening bei Änderung möglich - closed.
