### ISSUE TITLE
Kategorielose Zettel

### ISSUE THREAD

**Issue by NJona** [NJona/Kanban-Board#12]
Muss jeder Zettel eine Kategorie beinhalten, oder kann ein Zettel auch keiner Kategorie zugewiesen sein?

**Comment by highperformancedevelopments** [comment]
In Mail vom 13.10.2017 Antwort beim Kunden angefordert.

**Comment by highperformancedevelopments** [comment]
AW Kunde 13.10.2017:

Anforderung:
Jede Aufgabe soll einer Kategorie zugewiesen werden können.
Frage:
Muss jeder Zettel einer Kategorie zugehören, oder sind Zettel ohne Kategorie Statthaft?

> „Ohne Kategorie“ ist statthaft

**Comment by highperformancedevelopments** [comment]
Intern:
Eindeutig geklärt - closed.
