### ISSUE TITLE
Export der Daten nach Outlook

### ISSUE THREAD

**Issue by NJona** [NJona/Kanban-Board#13]
Soll es möglich sein einzelne Tasks zu exportieren, oder das komplette Kanban-Board?

**Comment by highperformancedevelopments** [comment]
In Mail vom 13.10.2017 Antwort beim Kunden angefordert.

**Comment by highperformancedevelopments** [comment]
AW Kunde 13.10.2017:

Anforderung:
Export der Aufgaben nach Outlook.
Frage:
Sollen die Aufgaben gesammelt oder selektiv exportiert werden? Bzw. soll dem User eine entsprechende Auswahl angeboten werden?

> Machen Sie uns einen Vorschlag.

**Comment by highperformancedevelopments** [comment]
Intern:
Vorschlag beides, durch User wählbar.
@NJona @ICarmine

**Comment by NJona** [comment]
Bis zum nächsten Release nicht relevant. Ich füge den Task zur Todo Liste hinzu.

**Comment by highperformancedevelopments** [comment]
Intern:
Rückmeldung Kunde in Mail vom 25.10.2017, dass Umsetzung erst im nächsten Release.

**Comment by NJona** [comment]
nicht mehr gefordert
