### ISSUE TITLE
Statistiken

### ISSUE THREAD

**Issue by NJona** [NJona/Kanban-Board#14]
Was für Statistiken sollen erstellt werden?

**Comment by highperformancedevelopments** [comment]
In Mail vom 13.10.2017 Antwort beim Kunden angefordert.

**Comment by highperformancedevelopments** [comment]
AW Kunde 13.10.2017:

Anforderung:
Es sollen Statistiken für einen Zeitraum erstellt werden können.
Frage:
Welche Statistiken sollen erstellt werden (Kennzahlen, Zeiträume)? In welcher Form soll die Darstellung erfolgen?

> Machen Sie uns einen Vorschlag. Was ist aus Sicht eines Planers interessant? Vermutlich eine Aussage zur Verweildauer, aber auch zur Anzahl, ebenfalls denkbar eine gewichtete Bearbeitungsdauer entsprechend der Priorität

**Comment by highperformancedevelopments** [comment]
Intern:
Brainstorming erforderlich. Vorschlag: Bearbeitunsdauer gesamt und nach Prio / Kategorie. Weitere Ideen?
@NJona @ICarmine

**Comment by NJona** [comment]
Bis zum nächsten Release nicht relevant, ich füge den Task zur Todo Spalte hinzu, dass wir ihn nicht vergessen.

**Comment by highperformancedevelopments** [comment]
Intern:
Rückmeldung an Kunden in Mail vom 25.10.2017
Umsetzung im nächsten Release.

**Comment by NJona** [comment]
Feature wird zum Release nicht fertig.
