### ISSUE TITLE
Task Historie

### ISSUE THREAD

**Issue by NJona** [NJona/Kanban-Board#15]
Soll in der Historie der Spaltenname hinzugefügt werden, den die Spalte zu diesem Zeitpunkt hatte, oder immer der aktuelle Spaltenname (falls sich dieser über die Zeit ändert)?

**Comment by highperformancedevelopments** [comment]
In Mail vom 13.10.2017 Antwort beim Kunden angefordert.

**Comment by highperformancedevelopments** [comment]
AW Kunde 13.10.2017:

Anforderung:
Die letzten 10.000 Aufgaben soll in Form einer Historie festgehalten werden.
Frage:
Beim Eintrag in die Historie wird der Spaltenname entsprechend mit dem Zeitpunkt der Verschiebung gespeichert. Wenn der Spaltenname zwischenzeitlich aktualisiert wird, sollen die Einträge der Historie auf den neuen Spaltennamen aktualisiert werden, oder bleibt der „damals“ aktuelle Name bestehen?

> Wenn die Spalte nur umbenannt wird, bleibt die Historie erhalten. Wird die Spalte gelöscht, wird auch die Historie gelöscht

**Comment by highperformancedevelopments** [comment]
Intern:
Frage eindeutig geklärt - closed.

**Comment by NJona** [comment]
Dies wirft die Frage auf, ob jeder Task eine Historie haben soll die Auskunft darüber gibt, zu welchem Zeitpunkt er wo war, oder ob jede Spalte eine Historie erhalten soll, die zeigt wann ein Task in ihr war.
