### ISSUE TITLE
Anzeige der Historie

### ISSUE THREAD

**Issue by highperformancedevelopments** [NJona/Kanban-Board#16]
Wie soll die Historie der Aufgaben dargestellt werden?

**Comment by highperformancedevelopments** [comment]
In Mail vom 13.10.2017 Antwort beim Kunden angefordert.

**Comment by highperformancedevelopments** [comment]
AW Kunde 13.10.2017:

Anforderung:
Die letzten 10.000 Aufgaben soll in Form einer Historie festgehalten werden.
Frage:
Wie soll die Historie dargestellt werden (Grafisch z.B. Tabelle oder Liste oder als eigene Spalte?

> Überraschen Sie uns.

**Comment by highperformancedevelopments** [comment]
Intern:
Erneut nachfragen zu späterem Zeitpunkt oder mein Vorschlag: Tabellarisch in extra Fenster.
@NJona @ICarmine

**Comment by NJona** [comment]
siehe #15

**Comment by highperformancedevelopments** [comment]
Intern:
Rückfrage beim Kunden in Mail vom 25.10.2017.
