### ISSUE TITLE
Tests für den TaskController

### ISSUE THREAD

**Issue by NJona** [NJona/Kanban-Board#25]
Aus TaskData TaskViews erstellen und zum Gridpane hinzufügen.

**Comment by NJona** [comment]
Maximal 8 Tasks pro Spalte.

**Comment by NJona** [comment]
Tests für den TaskController:

Methoden:

- createTaskViewForEeachColumnData: Hier sollte getestet werden, ob nach Aufruf der Methode gleich viel tasksData wie tasks (Views) vorhanden sind und ob tasks[0].getTaskData tasksData[0] entspricht, tasks[1].getTaskData = tasksData[1] usw...

- addTask: Hier sollte getestet werden, ob nach dem Aufruf der Methode ein neuer Task in dem tasks Array ist und ob ein neues taskData in tasksData ist. Außerdem muss der Rückgabewert überprüft werden, ob er dem neuen task entspricht

**Comment by janik2102** [comment]
Tests abgeschlossen
