### ISSUE TITLE
Hinzufügen der letzten Spalte

### ISSUE THREAD

**Issue by NJona** [NJona/Kanban-Board#27]
Die letzte Spalte soll laut Anforderung keine Begrenzung an Tasks in der Spalte besitzen. Falls nun 3 Spalten vorhanden sind und davon die letzte Spalte mehr als 8 Tasks (Standard Anzahl maximale Tasks) besitzt und anschließend eine vierte hinzugefügt wird, darf die dritte Spalte nur noch 8 Tasks besitzen, womit dadurch ein Fehler entsteht. 
Lösungsvorschlag: Die erste Spalte hat fest maximal 8 Tasks, die zweite Spalte als Doing Spalte maximal 1 Task, die letzte hat keine Begrenzung und falls nun eine vierte Spalte hinzugefügt wird, wird diese zwischen die zweite und dritte eingefügt und nicht mehr als neue letzte, da sie sowieso die "Coffee" Spalte darstellen soll und somit immer maximal 8 Tasks enthält.

**Comment by highperformancedevelopments** [comment]
Intern:

In Mail vom 02.11.2017 Antwort beim Kunden angefragt.

**Comment by NJona** [comment]
es sind nun 10 Spalten gefordert, die vor der letzten Spalte eingefügt werden
