### ISSUE TITLE
Zettel sollen in verschiedenen Farben eingefärbt sein

### ISSUE THREAD

**Issue by NJona** [NJona/Kanban-Board#28]
Farbe entspricht Kategorie, oder für jeden Task frei wählbare Farbe? Vordefinierte Farben, oder HexCode?

**Comment by highperformancedevelopments** [comment]
Intern:
War vom Kunden in der Anforderungs-Mail vorgegeben, jeder Zettel hat eine eigene Farbe 

> Neue Anforderung: Die Zettel in den Spalten sollen mit verschiedenen Farben eingefärbt werden können.

Farbwahl trotzdem mit KD abstimmen?

**Comment by NJona** [comment]
das war in Bezug auf die neuen Anforderungen

**Comment by highperformancedevelopments** [comment]
Ja schon klar, aber die haben doch geschrieben die verschiedenen Zettel in der Spalte - sprich jeder Zettel

**Comment by NJona** [comment]
Karten können auch über die Kategorie hinaus gefärbt werden
-> Lösungsvorschlag: Zettel kann per Hex gefärbt werden, Kategorie Titel wird in der Kategorie Farbe angezeigt
