### ISSUE TITLE
WIP individuell anpassen

### ISSUE THREAD

**Issue by NJona** [NJona/Kanban-Board#29]
woher weiß das Kanban-Board bei 10 Spalten, welches die WIP Spalte ist? Vorschlag: man kann in jeder Spalte individuell anpassen wie viele Zettel diese beinhalten kann.

**Comment by highperformancedevelopments** [comment]
Intern:
Antwort beim Kunden in Mail vom 07.11.2017 angefordert.

**Comment by NJona** [comment]
Lösungsvorschlag: in jeder Spalte kann die maximale Anzahl an Zetteln definiert werden -> User wählt die WIP Spalte selber
