### ISSUE TITLE
Test für den allgemeinen Controller

### ISSUE THREAD

**Issue by NJona** [NJona/Kanban-Board#31]
Tests für den allgemeinen Controller:

Methoden zu testen:

- initializeMenu: testen, ob anschließend "menuBar" oben im fullBorderPane enthalten ist

- createMenuBar: testen, ob MenuBar initialisiert wurde ( nicht null ist, sondern der Klasse MenuBar entspricht)

- createMenus: testen, ob die Menüs file und edit initialisiert wurden und der Klasse Menu entsprechen, außerdem ob der Name richtig ist. Zusätzlich testen, ob die beiden nach aufruf der Methode zu MenuBar hinzugefügt wurden

- create MenuItems: testen, ob alle MenuItems richtig erstellt wurden und jedes einenen Eventhandler enthält, der die korrekte Methode aufruft. Anschließend prüfen, ob die MenuItems dem richtigen Menu zugewiesen wurden.

- addColumn: testen, ob das richtige Gridpane der Spalte an die richtige Stelle der HBOX hinzugefügt wurde falls die maximale Anzahl der Spalten noch nicht erreicht wurde, außerdem testen, ob das MenuItem addColumn disabled wird, sobald die Anzahl der Spalten nach dem hinzufügen das maximum erreicht hat

- addEachColumnViewToBoardGridpane: prüfen, ob alle columnGridpanes zur HBox hinzugefügt wurden

-

**Comment by highperformancedevelopments** [comment]
@janik2102 ich übernehme dieses Issue komplett.

**Comment by highperformancedevelopments** [comment]
Tests in Form von BlackBoxTests durchgeführt und an die Metriken Abteilung samt Doku übergeben.
