### ISSUE TITLE
Tests für den SpaltenController

### ISSUE THREAD

**Issue by NJona** [NJona/Kanban-Board#4]
Verbinden der GUI Events mit dem Spalten Service

**Comment by NJona** [comment]
Time to Refactor

**Comment by NJona** [comment]
Tests für den ColumnController:

Methoden:
- createColumnViewForEeachColumnData: Hier sollte getestet werden, ob nach Aufruf der Methode gleich viel columnsData wie columns (Views) vorhanden sind und ob columns[0].getColumnData columnsData[0] entspricht, columns[1].getColumnData = columnsData[1] usw...

- addColumn: Hier sollte getestet werden, ob nach dem Aufruf der Methode ein neues Column in dem columns Array ist und ob ein neues columnData in columnsData ist. Außerdem muss der Rückgabewert überprüft werden, ob er dem neuen column entspricht

- handleRemoveColumn: Hier sollte getestet werden, ob das übergebene Column sowohl aus columns, sowie das columnData aus columnsData gelöscht wurde sofern die Spalte keine Tasks mehr beinhaltet
falls die Spalte noch Tasks beinhaltet muss außerdem getestet werden, ob sie eine ColumnNotEmptyException wirft

- addEachTaskViewToBoardGridpane: Hier sollte überprüft werden, ob anschließend jedes Spalten Gridpane die richtigen Task Gridpanes enthält (evtl viel Aufwand)

- addTask: überprüfen, ob der Task in die erste Spalte hinzugefügt wurde und ob der richtige Rückgabewert zurück gegeben wird

**Comment by janik2102** [comment]
@highperformancedevelopments übernehme diese Tests

**Comment by janik2102** [comment]
Tests abgeschlossen
