### ISSUE TITLE
Spaltenanzahl

### ISSUE THREAD

**Issue by NJona** [NJona/Kanban-Board#7]
Soll der Nutzer entscheiden können, ob 3 oder 4 Spalten angezeigt werden, oder kann dies vom Entwicklerteam festgelegt werden? (z.B. am Anfang immer 3 Spalten, mit einem + die Möglichkeit eine 4. hinzuzufügen und mit einem - die Möglichkeit diese wieder zu entfernen)

**Comment by highperformancedevelopments** [comment]
In Mail vom 13.10.2017 Antwort beim Kunden angefordert.

**Comment by highperformancedevelopments** [comment]
AW Kunde 13.10.2017:

Anforderung:
Der Nutzer soll 3-4 Spalten haben, welche frei benannt werden können.
Frage:
Benötigen Sie 3 oder 4 Spalten oder soll in der Anwendung eine Auswahl durch den Nutzer implementiert werden? Wenn ja, welche Anzahl soll der Default-Wert sein?

> Default-Wert 3 Spalten, durch den Nutzer auf 4 Spalten erweiterbar

**Comment by highperformancedevelopments** [comment]
Intern:
Eindeutig geklärt - closed.
