### ISSUE TITLE
Löschen eines Zettels

### ISSUE THREAD

**Issue by NJona** [NJona/Kanban-Board#8]
Muss der Nutzer die Möglichkeit haben einen Zettel zu löschen?
-> ansonsten verweilen die Zettel für immer in der letzten Spalte
falls ja:
- ist das löschen überall möglich, oder nur in der letzten Spalte?
- werden gelöschte Zettel auch aus der Historie gelöscht?

**Comment by highperformancedevelopments** [comment]
Rückfrage Intern:
@NJona 
Anzahl der Zettel in letzter Spalte = klar oder soll ich da auch nachfragen.
Zusammenhängend hiermit auch die Frage wie die Historie angezeigt werden soll oder?

**Comment by NJona** [comment]
Die Anforderung an die maximale Anzahl an Zettel in der letzten Spalte wurde schon geändert 
-> es gibt keine Begrenzung in der letzten Spalte

gerne auch die Frage, wie die Historie angezeigt wird

**Comment by highperformancedevelopments** [comment]
In Mail vom 13.10.2017 Antwort beim Kunden angefordert.

**Comment by highperformancedevelopments** [comment]
AW Kunde 13.10.2017:

Anforderung:
Jede Aufgabe soll auf einem Zettel festgehalten werden.
Frage:
Sollen Zettel gelöscht werden können? Wenn ja, soll dies in allen Spalten möglich sein? Wird ein Zettel gelöscht wird die Historie zu diesem ebenfalls gelöscht ?

> Ja, Zettel können gelöscht werden. Die Historie soll erhalten bleiben. Ob sie in die Statistiken einfließen, bitte ich Sie zu analysieren und uns einen guten Vorschlag zu machen.

**Comment by highperformancedevelopments** [comment]
Intern:
Zettel, welche gelöscht wurden extra in der Statistik aufführen, in der "normalen" Statistik haben die nichts verloren --> Verfälschung.

**Comment by NJona** [comment]
Sehe ich genauso
