### ISSUE TITLE
Zettelinhalt

### ISSUE THREAD

**Issue by NJona** [NJona/Kanban-Board#9]
Welche Attribute soll der Zettel alles beinhalten?
Vorschlag:
- Titel
- Beschreibung
- Verantwortlicher
- Priorität

**Comment by highperformancedevelopments** [comment]
Rückfrage Intern:
@NJona 
Verantwortlicher ist glaube ich hinfällig, da die Anwendung PERSONAl Kanban heißt also nur für den Nutzer selbt. Bitte Rü wegen der Anfrage.

**Comment by NJona** [comment]
@highperformancedevelopments da hast du Recht. Wird zumindest am Anfang nicht benötigt.

**Comment by highperformancedevelopments** [comment]
@NJona Dann lasse ich den Punkt Verantwortlicher raus und stelle die Anfrage mit den verbleibenden Punkten.

In Mail vom 13.10.2017 Antwort beim Kunden angefordert.

**Comment by highperformancedevelopments** [comment]
AW Kunde 13.10.2017:

Anforderung:
Jede Aufgabe soll auf einem Zettel festgehalten werden.
Frage:
Welche Attribute/Informationen soll der Zettel enthalten?
Vorschlag: Titel, Beschreibung, Priorität

> Fürs erste paßt es so wie Sie vorgeschlagen haben

**Comment by highperformancedevelopments** [comment]
Intern:
Eindeutig geklärt - closed.
